/**
 * Single source of truth for the Setaweet Archive.
 *
 * Text (title, year, description, links) lives here; the image / audio / video
 * / pdf file paths come from src/content/archive-media.json, generated by the
 * asset-import script from the real folders under src/assets and copied into
 * /public/archive/<slug>/.
 */

import mediaManifest from "@/content/archive-media.json";

export type ArchiveImage = {
  /** Path under /public, e.g. "/archive/alegnta/hero.jpg". Optional = placeholder. */
  src?: string;
  alt: string;
};

/** A named campaign/effort that lives inside a parent project's page. */
export type SubProject = {
  slug: string;
  title: string;
  /** Paragraphs separated by a blank line. */
  description: string;
  cover: ArchiveImage;
  images: ArchiveImage[];
  video?: string;
  audio?: string;
  pdf?: string;
  links?: string[];
};

export type Project = {
  slug: string;
  title: string;
  year: number;
  /** Paragraphs separated by a blank line. */
  description: string;
  /** Main image used on the home archive carousel. */
  cover: ArchiveImage;
  /** Gallery images shown on the project page. */
  images: ArchiveImage[];
  /** Optional embedded media found in the project folder. */
  video?: string;
  audio?: string;
  pdf?: string;
  /** External links (e.g. YouTube). */
  links?: string[];
  website?: string;
  /** Sub-projects rendered as their own sections on the project page. */
  subProjects?: SubProject[];
};

type MediaEntry = {
  cover: string | null;
  images: string[];
  video?: string;
  audio?: string;
  pdf?: string;
  subProjects?: Record<string, Omit<MediaEntry, "subProjects">>;
};

const media = mediaManifest as Record<string, MediaEntry>;

type SubProjectMeta = {
  slug: string;
  title: string;
  description: string;
  links?: string[];
};

type ProjectMeta = {
  slug: string;
  title: string;
  year: number;
  description: string;
  links?: string[];
  website?: string;
  subProjects?: SubProjectMeta[];
};

const META: ProjectMeta[] = [
  {
    slug: "monthly-circles",
    title: "Monthly Circles & Open Sessions",
    year: 2014,
    description:
      "Setaweet's Monthly Circles and Quarterly Open Sessions emerged after the movement's inception in July 2014 as a space for Ethiopian women advocating for gender equality and feminist solidarity. The gatherings grew in response to the death of sixteen-year-old Hanna Lalango in November 2014, which galvanized conversations around gender-based violence and women's safety.\n\nEvery second Tuesday of the month, women came together to share experiences and build support networks. As participation expanded, the initiative evolved into Setaweet Open Sessions — welcoming both women and men into broader discussions on feminism and gender justice, and contributing to the growth of grassroots feminist organizing in Ethiopia.",
  },
  {
    slug: "arif-abbat",
    title: "Arif Abbat",
    year: 2017,
    description:
      "Arif Abbat — 'great father' — was a photo competition implemented between 2017 and 2019 to promote positive representations of fatherhood and shared parenting in Ethiopian society. Participants submitted photographs reflecting gender equality, care work, and fathers' active involvement in raising children.\n\nThe first exhibition was held at the Addis Ababa Museum in December 2017, followed by #ArifAbbat 2.0 in Mekelle City in March 2019. Through visual storytelling and public exhibition, the project challenged traditional expectations around parenting roles and encouraged more equitable family dynamics.",
  },
  {
    slug: "min-lebsa-neber",
    title: "Min Lebsa Neber",
    year: 2018,
    description:
      "Min Lebsa Neber (#WhatSheWore) was a traveling exhibition implemented between 2018 and 2020 in Addis Ababa, Gondar, Wolaita, and Dire Dawa. It displayed clothes worn by survivors at the time of their sexual assault alongside personal testimonies shared by the survivors themselves.\n\nFirst presented at the Addis Ababa Museum in late 2018 — a collaboration between Setaweet, the Embassy of Sweden, and UN Women, with a final showcase at the Goethe-Institut — the exhibition confronted victim-blaming narratives and encouraged public dialogue on survivor experiences, accountability, and empathy.",
    links: ["https://youtu.be/WpmzhtqHhUw"],
  },
  {
    slug: "gendershops",
    title: "Gendershops",
    year: 2018,
    description:
      "The Gendershops were a feminist curriculum and workshop initiative implemented between 2018 and 2024 for secondary school and university students in Ethiopia. The participatory learning spaces explored femininities and masculinities, healthy relationships, self-esteem, beauty standards, and gender norms.\n\nConducted as interactive two-day workshops, the program reached more than 2,200 students across six schools in Addis Ababa between 2018 and 2019, later expanding to university students and young married women. By fostering dialogue around toxic masculinity and gender-based violence, it contributed to safer, more inclusive school and community environments.",
  },
  {
    slug: "writing-our-rights",
    title: "Writing Our Rights",
    year: 2019,
    description:
      "Setaweet organized the 1st Annual All-Women in Ethiopian Academia Conference (AWEAC) in Addis Ababa in November 2019 under the theme 'Writing Our Rights.' The conference brought together women researchers and academics from across Ethiopia to present work on representation, exclusion, democracy, media, arts, and gendered identities.\n\nIt created a platform for feminist academic dialogue, and Setaweet later published peer-reviewed articles by women scholars on gender, motherhood, intersectionality, and women's representation. The journal Writing our Rights strengthened feminist scholarship and expanded the visibility of women in Ethiopian academia.",
  },
  {
    slug: "alegnta",
    title: "Alegnta Hotline",
    year: 2019,
    description:
      "Operating from 2019 to 2025, the Alegnta Hotline was a free, nationwide psycho-social support service established by Setaweet to assist survivors of sexual and gender-based violence (SGBV). Accessible in Amharic, Afaan Oromo, and Sidama Afo, it was designed for inclusivity across diverse regions of Ethiopia.\n\nWith support from UN Women and Ethio Telecom, Alegnta evolved into a critical first-response mechanism, providing confidential, professional counseling and connecting callers to essential services including healthcare providers, legal institutions, one-stop centers, and in-person counseling resources. By mitigating the long-term psychological effects of violence — promoting recovery, resilience, and informed decision-making — and restoring a sense of agency and accessible pathways to support, it strengthened community responses to SGBV.",
    links: ["https://youtu.be/MU6e4660QIM", "https://youtu.be/g5vllZHto6U"],
  },
  {
    slug: "meqenet",
    title: "MeQenet",
    year: 2020,
    description:
      "Launched in 2020, MeQenet is Setaweet's talk-show-style documentary series that first aired on Arts TV before continuing on YouTube to reach a broader audience. The series engaged with everyday Ethiopian realities through a distinctly feminist lens, interrogating social, cultural, and political issues while challenging dominant narratives.\n\nBy combining dialogue, critical analysis, and storytelling, MeQenet created a reflective space that highlights the gendered dimensions of societal issues and raises fundamental questions about feminism in the Ethiopian context — contributing to a localized feminist agenda and strengthening grassroots women's movements.",
    links: [
      "https://youtu.be/AXlV5KNclfI",
      "https://youtube.com/playlist?list=PL3nTdsiMImry_Z6Zt8b2cmg6UVXT7gh-8",
    ],
  },
  {
    slug: "data-project",
    title: "Data Project",
    year: 2021,
    description:
      "The Data Project was launched in 2021 to strengthen gender-based violence reporting systems and improve data management within police institutions in Ethiopia. As part of the initiative, Setaweet developed the Alegnta Mobile App, enabling survivors and witnesses to anonymously report incidents in public and private spaces.\n\nIn collaboration with the digital marketing company social.ly, the project developed and updated software used by the Addis Ababa Police Commission to improve GBV data collection and case management. Installed across sub-city police stations, it helped standardize intake forms and document cases more effectively — supporting more responsive, survivor-centered approaches.",
  },
  {
    slug: "tesfaweet",
    title: "Tesfaweet",
    year: 2021,
    description:
      "Tesfaweet, the Married Girls' Project, was implemented in Debre Tabor and the South Gondar area beginning in 2021 to support girls and young women affected by child marriage. It provided empowerment training, livelihood support, and raw materials that enabled participants to establish micro-poultry farms and small-scale spice businesses.\n\nBuilding on the success of CARE Ethiopia's TESFA Project and focusing on married girls in Farta Woreda, the initiative addressed inequalities in access to education, economic opportunity, and social support — creating opportunities for long-term empowerment and social inclusion.",
  },
  {
    slug: "policy-dialogues",
    title: "Policy Dialogues",
    year: 2021,
    description:
      "The Policy Dialogues series was implemented between January 2021 and June 2022 in Addis Ababa through a collaboration between Setaweet and FES-FMCC to advance feminist policy engagement and (re)politicize gender equality in Ethiopia. The initiative organized five major dialogues on constitutional reform, gender and migration, women and conflict, peace-building, and feminist movement-building.\n\nBringing together academics, activists, women's rights organizations, and legal experts, the dialogues strengthened collaboration and supported shared feminist agendas — expanding feminist policy discourse through platforms for alliance-building, knowledge-sharing, and collective advocacy.",
  },
  {
    slug: "advocacy-campaign",
    title: "Advocacy Campaigns",
    year: 2022,
    description:
      "Setaweet's Advocacy Campaigns were a series of interlinked public initiatives implemented across Addis Ababa and other major cities between 2022 and 2023, addressing the experiences of women affected by gender-based violence during the war. Working across radio, television, social media, exhibitions, and public wall art, the campaigns amplified survivors' voices while fostering national awareness and a shared call to accountability.\n\nThree efforts made up the initiative: the Ahunim Alrefedem and Lik Aydelem campaigns, and the Unveiling Stories exhibition.",
    subProjects: [
      {
        slug: "ahunim-alrefedem",
        title: "Ahunim Alrefedem",
        description:
          "Implemented across Addis Ababa and other major cities between December 2022 and March 2023, Ahunim Alrefedem ('It's still not late') framed the campaign as a call to accountability and a refusal to accept silence around wartime gender-based violence.\n\nThrough radio ads, social media outreach, curated screenings of the Misikir documentary, and public wall art and murals, the campaign amplified survivors' voices, engaging mainstream platforms including Sheger 102.1 FM and the Endalk ena Mahder program — where members of the Setaweet team discussed the campaign's significance and their experience producing Misikir.",
        links: ["https://youtu.be/Gkxkp6VoSEQ"],
      },
      {
        slug: "lik-aydelem",
        title: "Lik Aydelem",
        description:
          "Implemented as a national campaign across Ethiopia in 2022, Lik Aydelem ('It Is Not Normal') sought to challenge prevailing misconceptions around gender-based violence and its impact on individuals and communities. It raised public awareness of the many forms GBV can take — physical, emotional, psychological, sexual, and economic abuse — emphasizing that violence often extends beyond commonly recognized acts.\n\nThrough accessible public messaging and advocacy, the campaign encouraged critical reflection on social norms and behaviors that normalize, excuse, or conceal violence against women and girls, and directed survivors and community members to the Alegnta hotline for information, psychosocial support, and referrals to relevant services. By strengthening public understanding of gender-based violence and awareness of available support, Lik Aydelem contributed to broader national efforts to prevent violence, support survivors, and promote accountability.",
      },
      {
        slug: "unveiling-stories",
        title: "Unveiling Stories",
        // Per source content: image only, no written copy.
        description: "",
      },
    ],
  },
  {
    slug: "womens-national-agenda",
    title: "Women's National Agenda",
    year: 2022,
    description:
      "The Women's National Agenda convened Ethiopian women from across the country around feminist organizing and movement-building through two national gatherings: the National Women's Forum and the National Women's Conference.",
    subProjects: [
      {
        slug: "national-womens-forum",
        title: "National Women's Forum",
        description:
          "The National Women's Forum, held in Bishoftu in June 2022, brought together close to one hundred women from several regions of Ethiopia to deliberate on contemporary women's issues and feminist organizing. It created a national space for women's rights advocates, activists, and organizations to reflect on key social, political, and gender-related challenges.\n\nBy encouraging collaboration and alliance-building across diverse regional and organizational backgrounds, the forum strengthened feminist networks across the country and contributed to a stronger, more connected feminist movement through collective strategizing, dialogue, and long-term movement-building.",
      },
      {
        slug: "national-womens-conference",
        title: "National Women's Conference",
        description:
          "The National Women's Conference followed in April 2023 at the Hilton Hotel in Addis Ababa — a two-day gathering of hundreds of Ethiopian women focused on feminist movement-building and peace-building. It featured keynote speeches, documentary screenings, breakout sessions, and experience-sharing on conflict, humanitarian response, women's participation in peace processes, African feminism, and digital feminist organizing, with participants reflecting on the role of women in the upcoming national dialogue process.\n\nAs the concluding event in the Policy Dialogues series, the conference created a platform for women's rights advocates and organizations from across the country to learn from one another, strengthen solidarity, and advance collective advocacy, sisterhood, and movement-building in Ethiopia.",
      },
    ],
  },
  {
    slug: "meseret",
    title: "Meseret",
    year: 2022,
    description:
      "Meseret was implemented from August 2022 to March 2025 in Tigray and Addis Ababa in partnership with Addis Powerhouse, with financial support from the Spanish Cooperation and in collaboration with local organizations including N4ED, Teki Paper Bags, Yamlak Lijoch Aras Bet Foundation, and Chura Abugida Artistic Association. The project strengthened feminist movements through women's circles that created supportive spaces to discuss social issues, exchange experiences, and build solidarity at the grassroots level.\n\nThrough weekly feminist dialogue sessions — six per group — business-development trainings, and project-planning workshops, Meseret combined movement-building with economic empowerment for women from marginalized and conflict-affected communities, supporting new mothers, deaf women workers, and survivors of conflict-related sexual violence. The content was tailored to each group, and for the group in Adigrat it was interpreted into Tigrinya with the support of an external facilitator — strengthening local leadership across regions.",
  },
  {
    slug: "misikir",
    title: "Misikir",
    year: 2023,
    description:
      "Misikir is a feminist documentary film developed between 2023 and 2025 across the Afar, Amhara, Benishangul-Gumuz, and Tigray regions of Ethiopia, centering the lived experiences of women in displacement camps directly impacted by armed conflict. Through an intimate, grounded approach, the film documents the consequences of conflicts that began in November 2020 in Tigray and the continued effects of inter-communal violence in Oromia and Benishangul-Gumuz.\n\nThe title — derived from the Amharic word for 'witness' — foregrounds women as authoritative narrators of their own histories. Rather than reproducing reductionist portrayals of suffering, Misikir prioritizes specificity and agency, offering a nuanced, ethically grounded counter-narrative that fosters empathy and solidarity among women.",
    links: ["https://youtu.be/mPhti0ydKLk", "https://youtu.be/cwBnIiQaljQ"],
  },
  {
    slug: "trauma-healing",
    title: "Trauma Healing Work",
    year: 2023,
    description:
      "Setaweet's Trauma Healing Work was implemented in Adigrat, Tigray in late 2023 and expanded to Debre Birhan in 2025–2026 to support conflict-affected women, families, and internally displaced communities through trauma-informed interventions. The project reached over 100 women in Adigrat and more than 700 women and men in Debre Birhan through workshops, group counseling, and community-based psychosocial support.\n\nWorking with local partners including YWCA Debre Birhan, the initiative trained facilitators to lead trauma-healing sessions and distributed essential items such as raincoats and children's rain boots to displaced families — strengthening community resilience by combining healing, community care, and humanitarian assistance, with documentation continuing into 2026.",
  },
  {
    slug: "transitional-justice",
    title: "Transitional Justice",
    year: 2024,
    description:
      "The Transitional Justice initiative was implemented in Addis Ababa in March 2024 through two consecutive gatherings focused on women's experiences in conflict and gender-responsive transitional justice. The first event, YeSetoch Wulo, brought together 45 women frontline responders, human rights advocates, and women's rights organizations from six regions to reflect on transitional justice.\n\nA two-day Writeshop, 'Input to Transitional Justice and Strategic Litigation Efforts,' then convened 25 participants to discuss feminist perspectives on Ethiopia's transitional justice process. The initiative produced a feminist position statement advocating a gender-responsive approach and strengthened collaboration among women working on conflict and human rights.",
  },
  {
    slug: "humanitarian-support",
    title: "Humanitarian Support",
    year: 2024,
    description:
      "Setaweet's Humanitarian Support project was implemented in November 2024 at the Shimelaku IDP Camp in Dabat Woreda, North Gondar, Amhara Region, to support conflict-affected internally displaced women and girls. It focused on women-headed households, survivors of gender-based violence, women with disabilities, and adolescent girls through dignity kits and targeted cash assistance.\n\nA total of 800 women and girls received dignity kits meeting UNFPA standards, while 340 women-headed households received two months of cash assistance totaling 14,000 Birr per household. Recognized by the Bureau of Women and Social Affairs, the project marked one of the first large-scale gender-sensitive humanitarian interventions in the area and strengthened Setaweet's capacity in feminist humanitarian response.",
    links: ["https://youtu.be/S1bBj_ehuT0"],
  },
  {
    slug: "leddoki",
    title: "Leddoki",
    year: 2025,
    description:
      "Leddoki was implemented in Hawassa and other cities in the Sidama Region in 2025 as part of a project titled 'Promoting Inclusiveness in Society through Rights-Based Research, Dialogue, and Advocacy.' The initiative focused on strengthening grassroots women's movements and advancing gender justice through community dialogue, advocacy, and capacity-building.\n\nBy establishing Setaweet circles and facilitation training, the project created safe spaces for discussions around gender-based violence and strengthened local leadership — increasing volunteer engagement and expanding local advocacy networks for more inclusive, sustainable community responses to gender inequality.",
  },
  {
    slug: "negari",
    title: "Negari",
    year: 2024,
    description:
      "Negari is powered by the Setaweet Movement — a contemporary Ethiopian feminist collective dedicated to advocacy, truth-telling, and memorialization. The project documents gender-based violence against women in conflict-affected regions, contributing to national healing and reconciliation.\n\nBuilt on extensive truth-seeking across affected regions, its survivor testimonies serve as historical records. Negari is not just an exhibition — it is a call to remember, to reflect, and to act.",
  },
];

export const projects: Project[] = META.map((m) => {
  const assets = media[m.slug] ?? { cover: null, images: [] };
  return {
    slug: m.slug,
    title: m.title,
    year: m.year,
    description: m.description,
    links: m.links,
    website: m.website,
    cover: { src: assets.cover ?? undefined, alt: `${m.title} cover` },
    images: assets.images.map((src, i) => ({ src, alt: `${m.title} image ${i + 1}` })),
    video: assets.video,
    audio: assets.audio,
    pdf: assets.pdf,
    subProjects: m.subProjects?.map((s) => {
      const sub = assets.subProjects?.[s.slug] ?? { cover: null, images: [] };
      return {
        slug: s.slug,
        title: s.title,
        description: s.description,
        links: s.links,
        cover: { src: sub.cover ?? undefined, alt: `${s.title} cover` },
        images: sub.images.map((src, i) => ({ src, alt: `${s.title} image ${i + 1}` })),
        video: sub.video,
        audio: sub.audio,
        pdf: sub.pdf,
      };
    }),
  };
});

export const projectsBySlug: Record<string, Project> = Object.fromEntries(
  projects.map((p) => [p.slug, p])
);

/** Ascending list of distinct years present in the archive. */
export const archiveYears: number[] = Array.from(new Set(projects.map((p) => p.year))).sort(
  (a, b) => a - b
);
